### ISSUE TITLE
higherBal的问题

### ISSUE THREAD

**Issue by huyutuo** [openacid/paxoskv#1]
您好
在phase1 与 phase2阶段都有下面这段代码，我理解的是如果不能够得到多数派支持，便返回一个Bal更高的消息，这里higherBal能够保证比proposer的值高，但不保证在所有的replies中是最高的，这里如果返回一个在replies中Bal值最高的是不是更好那？ 还是我对paxos的过程理解错了？（刚开始学习paxos😂🙈)
感谢您的回答
```
if !p.Bal.GE(r.LastBal) {
			higherBal = *r.LastBal
			continue
		}
```

```
if err != nil {
			p.Bal.N = higherBal.N + 1
			continue
		}

```

**Comment by drmingdrmer** [comment]
能返回最高的当然最好啦. 但是paxos是要求不能联系到全部的replica就能正常工作, 最差情况下只能返回联系到的replica中最高的. 这样也能保证正确工作, 但不能保证是最高效的工作🤔.

**Comment by huyutuo** [comment]
```
func (p *Proposer) Phase1(acceptorIds []int64, quonum int) (*Value, *BallotNum, error) {
	replies := p.rpcToAll(acceptorIds, "Prepare")

	ok := 0
	highterBal := *p.Bal
	maxVoted := &Acceptor{VBal: &BallotNum{}}

	for _, r := range replies {
		pretty.Logf("Proposer : handing Prepare reply : %s", r)

		// 如果当前的Bal不大于acceptor中的lastBal则返回一个 acceptor中的LastBal
		if !p.Bal.GE(r.LastBal) {
			highterBal = *r.LastBal
			continue
		}

		pretty.Logf("r.Vbal : %s,  maxVoted.VBal : %s", r.VBal, maxVoted.VBal)
		if r.VBal.GE(maxVoted.VBal) {
			maxVoted = r
		}

		ok += 1
		// 如果得到多数派支持，则返回一个VBal值最大的Val
		if ok == quonum {
			return maxVoted.Val, nil, nil
		}
	}
return nil, &highterBal, ErrorNotEnoughQuorum
}

```
在Phase1中，如果没有得到多数派支持，会`return nil, &highterBal, ErrorNotEnoughQuorum`， 在RunPaxos中就会执行到`p.Bal.N = higherBal.N + 1`。 在Phase1中对highterBal的处理是
```
if !p.Bal.GE(r.LastBal) {
			highterBal = *r.LastBal
			continue
}
```
我理解的是这样也不能保证highterBal是在联系到的replica中最高的，这样只能保证是在联系到的replica中比Proposer高的最后处理的一个，换成这样是不是就可以保证 highterBal是在所有联系到的replica中最高的.
```
if !p.Bal.GE(r.LastBal) {
         if !highterBal.GE(r.LastBal) {
             highterBal = *r.LastBal
        }
	continue
}
```
感谢~

**Comment by drmingdrmer** [comment]
啊对...sorry这里确实有点问题. 应该是比较higherBal跟r.LastBal; p.Bal的比较可以去掉了. 因为最开始把p.Bal赋值给higherBal了.
原来那么写性能低了些, 要多重试几次, 正确性还是没问题的.

多谢提醒, 我修改下:DDD

**Comment by drmingdrmer** [comment]
上面说错了🤔...p.Bal的比较不能去掉. 是否是合法的reply还是要比较p.Bal

**Comment by huyutuo** [comment]
好，感谢回答~🙈🙈
