### ISSUE TITLE
有个可能比较傻的疑问想请教下

### ISSUE THREAD

**Issue by shenjiajia1225** [openacid/paxoskv#17]
假如有3个Accepter（1,2,3），2个proposer。
proposer1始终和accepter1,2通讯，proposer2始终和accepter2,3通讯。
下面是一个按时序的通讯顺序：
proposer1发出prepare(1),提案编号1
proposer2发出prepare(2),提案编号2
proposer1发出accept(1,100), 提案1，值100。Accept1接受，Accept2拒绝
proposer2发出accept(2,200), 提案2，值200。Accept2,3都接受
proposer1发出prepare(3),提案编号3，此时他应该获取下次应该accept的值是200
proposer1发出accept(3,200), Accept1,2都接受了
proposer2发出prepare(4)，此时会把Accept2,3虽然返回的值一致，但是这个值被接受的提案编号不一致，是不是他下次accept时应该使用 accept(4,200) ?
如果上一步中proposer2使用accept(4,200)提交时，那下一次proposer1在执行时也会一直用更高的提案编号同样的值提交，两个一直这样循环下去？
找不到哪里提问合适一点，就放这了，大佬见谅：）

**Comment by drmingdrmer** [comment]
你的问题挺好的，涉及到了paxos容易被忽略的v-rnd的问题。
实际上不同v-rnd的值应该认为你是不同的， 这样很多问题就变得明显的。

> proposer2发出prepare(4)，此时会把Accept2,3虽然返回的值一致，但是这个值被接受的提案编号不一致，是不是他下次accept时应该使用 accept(4,200) ?

是的

> 如果上一步中proposer2使用accept(4,200)提交时，那下一次proposer1在执行时也会一直用更高的提案编号同样的值提交，两个一直这样循环下去？

这时p2如果收到了2个accept的reply， 就可以停下了。 这个paxos实例已经提交了一个值，不再可变了。不知在你的问题里为何还要继续运行？

**Comment by shenjiajia1225** [comment]
谢谢大佬回复。
之前我看文章没理解，当时的疑惑是这样的，在针对有多个提案（value1，value2，。。。）的情况下，当提案value1一致后，下一个新的提案value2被提出时，虽然用了一个新的ProposalID，但是acceptor返回了之前提案的value1，按照phase2描述，只能用acceptor返回的value1在提交accept，这样感觉新的提案永远提不出去（每次prepare都返回之前通过的那个value，文章phase1里描述prepare只需要一个ProposalID）。
看了一些文章和介绍，现在我这样理解对不对：
每个value被提出时，实际应该都要对应一个paxos实例，一个paxos实例对应一次phase1,2过程，用来保证一个paxos实例达成一致（一个paxos实例是不是可以认为是一个log序列数组中的一个槽位）
所以实际在使用中，每次prepare的时候除了要一个ProposalID外，**还需要一个paxos实例ID**，最后对这个实例ID达成一致。
下一个新的value被提出时要用一个新的paxos实例ID和一个新的ProposalID。
可能存在多个server使用同一个paxos实例ID去prepare，这时需要用ProposalID去保证针对这个paxos实例ID的value的最终一致性。

**Comment by drmingdrmer** [comment]
> 每个value被提出时，实际应该都要对应一个paxos实例，一个paxos实例对应一次phase1,2过程，用来保证一个paxos实例达成一致（一个paxos实例是不是可以认为是一个log序列数组中的一个槽位）

就酱婶的!

在这个paxoskv里实例的id是key和key的版本. 一个key的多个版本就类似log slot了:
https://github.com/openacid/paxoskv/blob/db0a378355a3dd7a64c36e9e048d162afd2eead6/proto/paxoskv.proto#L34-L70

**Comment by shenjiajia1225** [comment]
恩现在看的有点感觉了，谢谢大佬：）
