### ISSUE TITLE
请问 Prepare handle 中为什么不用消除引用

### ISSUE THREAD

**Issue by czhWellOptimized** [openacid/paxoskv#20]
https://github.com/openacid/paxoskv/blob/db0a378355a3dd7a64c36e9e048d162afd2eead6/paxoskv/impl.go#L242
https://github.com/openacid/paxoskv/blob/db0a378355a3dd7a64c36e9e048d162afd2eead6/paxoskv/impl.go#L254
在 Accept 做了消除引用而 Prepare 没有做，是因为 Accept 的 reply 在最后会被读出来，而 Prepare 的 reply 只是一个中间结果的原因吗？

**Comment by czhWellOptimized** [comment]
那Prepare返回的这个引用 可能会存在并发读写的数据竞争吗？因为我看后续对返回的Acceptor(reply)的操作没有上锁

**Comment by drmingdrmer** [comment]
这一段一直拿着锁呢:
https://github.com/openacid/paxoskv/blob/db0a378355a3dd7a64c36e9e048d162afd2eead6/paxoskv/impl.go#L240-L248

acceptor 是被浅copy出来的, 里面的字段都是替换操作, 所以没有问题.

并发这块不用太在意了, 不是做这个项目的目的...
